# One Hot Encoding (OHE)

**One Hot Encoding** is a technique to convert categorical text data into a binary numeric format that machine learning models can process.

### Key Idea
Each unique word (token) gets its own column. For a given word, its column is set to `1` and all other columns are `0`.

### Why do we need it?
- Machine learning models work with **numbers**, not strings.
- OHE avoids implying a false **ordinal relationship** between words (e.g., encoding cricket=1, movie=2 would wrongly suggest movie > cricket).

### Drawbacks
- **High dimensionality** — large vocabulary = many columns (sparse).
- **No semantic meaning** — words with similar meanings get completely different vectors.
- **Out-of-vocabulary (OOV)** — unseen words at inference time cannot be encoded.

## Step 1: Import Libraries

We use `OneHotEncoder` from **scikit-learn** to perform encoding, and **NumPy** for numerical operations.

In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

## Step 2: Define the Corpus

A **corpus** is a collection of text documents. Here we define 4 simple sentences that share a common vocabulary.

In [2]:
documents = ["people watch movie", 
             "people watch cricket", 
             "people like movie", 
             "people like cricket"]

## Step 3: Tokenize the Documents

**Tokenization** splits each sentence into individual words (tokens).

- `.lower()` — converts text to lowercase so `Movie` and `movie` are treated as the same word.
- `.split()` — splits the sentence by whitespace into a list of words.

In [3]:
tokens = [sentence.lower().split() for sentence in documents]
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

## Step 4: Prepare Words for the Encoder

`OneHotEncoder` expects a **2D array** as input — each word must be wrapped in its own list `[word]`.

We flatten all tokens from all sentences into a single list of single-word lists.

In [4]:
all_words = [[word] for sentence in tokens for word in sentence]
all_words

[['people'],
 ['watch'],
 ['movie'],
 ['people'],
 ['watch'],
 ['cricket'],
 ['people'],
 ['like'],
 ['movie'],
 ['people'],
 ['like'],
 ['cricket']]

## Step 5: Create and Configure the Encoder

- `OneHotEncoder` — the encoder object from scikit-learn.
- `sparse_output=False` — by default the encoder returns a **sparse matrix** (memory-efficient but harder to read). Setting this to `False` returns a regular dense **NumPy array**, which is easier to inspect and visualize.

In [5]:
encoder = OneHotEncoder(sparse_output=False)

## Step 6: Fit the Encoder on the Vocabulary

`.fit()` scans all the words and learns the **vocabulary** — the set of all unique tokens.

This step does **not** transform anything yet; it only builds the internal mapping of word → column index.

In [6]:
encoder.fit(all_words)

OneHotEncoder(sparse_output=False)

## Step 7: Inspect the Vocabulary

`encoder.categories_[0]` returns the list of all unique words the encoder discovered, sorted alphabetically.

Each word corresponds to one column in the one-hot encoded output.

In [7]:
print("Vocabulary:", encoder.categories_[0])

Vocabulary: ['cricket' 'like' 'movie' 'people' 'watch']


## Step 8: Transform and Display Encoded Sentences

`.transform()` converts each word in a sentence into its one-hot vector.

For each sentence:
- Each word becomes a row vector with a `1` in the column corresponding to that word, and `0` everywhere else.
- The output shape per sentence is `(num_words_in_sentence, vocab_size)`.

**Reading the output:** if the vocabulary is `['cricket', 'like', 'movie', 'people', 'watch']`, then the word `movie` is represented as `[0, 0, 1, 0, 0]`.

In [8]:
for sentence in tokens:
    encoded = encoder.transform([[word] for word in sentence])
    print("\nSentence:", sentence)
    print(encoded)


Sentence: ['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

Sentence: ['people', 'watch', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]

Sentence: ['people', 'like', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

Sentence: ['people', 'like', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


## Summary

| Step | Action | Purpose |
|------|--------|---------|
| 1 | Import libraries | Load `OneHotEncoder` from scikit-learn |
| 2 | Define corpus | Collect the text documents |
| 3 | Tokenize | Split sentences into individual words |
| 4 | Prepare 2D word list | Format words as `[[word], ...]` for the encoder |
| 5 | Create encoder | Initialize `OneHotEncoder(sparse_output=False)` |
| 6 | Fit encoder | Learn the vocabulary from all words |
| 7 | Inspect vocabulary | See all unique words and their column positions |
| 8 | Transform & display | Encode each sentence word-by-word into binary vectors |

> **Note:** One Hot Encoding is best suited for **low-cardinality** categorical features. For large vocabularies, consider **Bag of Words**, **TF-IDF**, or **Word Embeddings** instead.